#! /bin/bash

[ -z "$1" ] && echo "Usage: $0 VERSION" && exit 1
VERSION="${1}"
FILENAME=dist/netpbm-"${VERSION}".tar.xz
[ ! -f "${FILENAME}" ] && echo "${FILENAME} not found" && exit 1

gh release create v${VERSION} -t netpbm-${VERSION} -n "netpbm-${VERSION} with userguide included" "${FILENAME}"
